#!/bin/bash
#set -x
export PATH=/usr/bin:/bin:/usr/sbin:/sbin
currentUser=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ { print $3 }' )
uid=$(id -u "$currentUser")
runAsUser() {
  if [ "$currentUser" != "loginwindow" ]; then
    launchctl asuser "$uid" sudo -u "$currentUser" "$@"
  else
    echo "no user logged in"
    exit 1
    fi
}
runAsUser defaults write com.microsoft.Word kSubUIAppCompletedFirstRunSetup1507 -bool TRUE
runAsUser defaults write com.microsoft.Excel kSubUIAppCompletedFirstRunSetup1507 -bool TRUE
runAsUser defaults write com.microsoft.Powerpoint kSubUIAppCompletedFirstRunSetup1507 -bool TRUE
runAsUser defaults write com.microsoft.onenote.mac kSubUIAppCompletedFirstRunSetup1507 -bool TRUE
